Feat/add model in schema
dnum-mi/referentiel-applications pull request #120
Opened 2024-11-13 10:43 UTC by Carolinedanslesnuages

2024-11-22 17:13 UTC, this-is-tobi commented on server/src/application/application.service.ts
>      });
Y'a une raison pour faire 2 fois le même appel en DB ?

2024-11-22 18:07 UTC, this-is-tobi commented on server/src/external-source/external-source.controller.ts
> +    const ownerId = req.user ? req.user.keycloakId : 'f15d1c13-8198-4ca5-a180-94656e20d568';
Une raison pour fallback sur un `ownerId` hardcodé ?

2024-11-22 18:08 UTC, this-is-tobi commented on server/src/user/entities/user.entity.ts
> +    KeycloakId: string;
Plutôt `keycloakId` que `KeycloakId` non ?

2024-11-23 19:57 UTC, Carolinedanslesnuages commented
voici un exemple pour tester le POST APPLICATION

```

{
  "status": 201,
  "message": "Application créée avec succès",
  "data": {
    "id": "7c570cb0-c800-4c54-bdf9-0c5611a08d2b",
    "label": "My Application",
    "shortName": "short-app-name",
    "logo": "http://example.com/logo.png",
    "description": "An amazing application",
    "url": "http://localhost:8080/applications/7c570cb0-c800-4c54-bdf9-0c5611a08d2b",
    "uri": "http://localhost:3500/api/v2/applications/7c570cb0-c800-4c54-bdf9-0c5611a08d2b",
    "purposes": [
      "finance",
      "HR"
    ],
    "tags": [
      "tag1",
      "tag2"
    ],
    "lifecycleId": "4b08570f-d9d1-49f8-895f-35d97400f9d4",
    "metadataId": "b353bde1-5f9c-4f4c-9caf-bdfa6b2d9712",
    "parentId": null,
    "ownerId": "f15d1c13-8198-4ca5-a180-94656e20d568",
    "lifecycle": {
      "id": "4b08570f-d9d1-49f8-895f-35d97400f9d4",
      "status": "under_construction",
      "firstProductionDate": "2023-11-22T00:00:00.000Z",
      "plannedDecommissioningDate": "2025-12-31T00:00:00.000Z",
      "metadataId": "b353bde1-5f9c-4f4c-9caf-bdfa6b2d9712",
      "metadata": {
        "id": "b353bde1-5f9c-4f4c-9caf-bdfa6b2d9712",
        "createdAt": "2024-11-23T19:50:24.336Z",
        "updatedAt": "2024-11-23T19:50:24.337Z",
        "createdById": "f15d1c13-8198-4ca5-a180-94656e20d568",
        "updatedById": "f15d1c13-8198-4ca5-a180-94656e20d568",
        "dataOwnerId": null
      }
    },
    "metadata": {
      "id": "b353bde1-5f9c-4f4c-9caf-bdfa6b2d9712",
      "createdAt": "2024-11-23T19:50:24.336Z",
      "updatedAt": "2024-11-23T19:50:24.337Z",
      "createdById": "f15d1c13-8198-4ca5-a180-94656e20d568",
      "updatedById": "f15d1c13-8198-4ca5-a180-94656e20d568",
      "dataOwnerId": null
    },
    "actors": [
      {
        "id": "0fcb1fdc-f5cb-4b99-afdf-d9a53fd6435d",
        "role": "admin",
        "userId": "f15d1c13-8198-4ca5-a180-94656e20d568",
        "organizationId": "83d19eda-0b83-45e7-80b7-fc0ba08fbe9e",
        "applicationId": "7c570cb0-c800-4c54-bdf9-0c5611a08d2b"
      }
    ],
    "compliances": [
      {
        "id": "939c301c-3221-4e83-9104-4b7d950c9082",
        "type": "regulation",
        "name": "GDPR",
        "status": "compliant",
        "validityStart": "2023-01-01T00:00:00.000Z",
        "validityEnd": "2025-01-01T00:00:00.000Z",
        "scoreValue": "85",
        "scoreUnit": "%",
        "notes": "Notes about the compliance",
        "metadataId": null,
        "applicationId": "7c570cb0-c800-4c54-bdf9-0c5611a08d2b"
      }
    ]
  }
}

```

2024-11-25 10:16 UTC, thomashbrnrd commented on server/prisma/schema/applications.prisma
> +  id                       String     @id @default(uuid())
Je pense qu'on devrait utiliser des clés :
```js
id    Int    @id @default(autoincrement())
```
plutôt que des uuid.

2024-11-25 10:42 UTC, thomashbrnrd commented on server/prisma/schema/users.prisma
> +model User {
Je pense que l'user devrait avoir un id unique "standard" pas sur qu'on puisse utiliser l'email comme foreign key si ?

2024-11-25 10:44 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +      return { status: 201, message: "Application créée avec succès", data: newApplication };
Est ce que le message n'est pas un peu redondant avec le status code 201 ?

2024-11-25 10:47 UTC, thomashbrnrd commented on server/src/auth/auth.service.ts
> +    async authenticate(accessToken: string): Promise<User> {
Je suis d'accord, de plus je ne pense pas qu'on ai besoin de cette méthode ?

2024-11-25 10:49 UTC, thomashbrnrd requested changes
Si on utilise krakend, il y a des choses qui ne sont pas nécessaires.

2024-11-25 11:03 UTC, this-is-tobi commented on server/prisma/schema/applications.prisma
> +  id                       String     @id @default(uuid())
Qu'est ce qui te fait préférer un nombre incrémenter plutôt qu'un  UUID ?

2024-11-25 11:04 UTC, this-is-tobi commented on server/src/app.module.ts
> +    KeycloakConnectModule.register({
C'est justement le but que de valider que le token est correct pour protéger les routes d'API non ?

2024-11-25 11:05 UTC, this-is-tobi commented on server/src/auth/jwt.strategy.ts
> +      secretOrKeyProvider: jwksRsa.passportJwtSecret({
Ahh ! Je comprends mieux, le but c'est de faire valider le token Keycloak par Krakend en amont de l'API ?

2024-11-27 15:51 UTC, thomashbrnrd commented on package.json
> +  "dependencies": {
Es tu certaine que ces changes soit nécessaires ?

2024-11-27 15:52 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +
Je ne suis pas certain du nombre de sauts de lignes ici, un petit coup de prettier serait bienvenu

2024-11-28 10:07 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +  private getDecodedToken(req: any): any {
Ce n'est pas nécessaire car krakend s'occupe déjà de la validation du JWT

2024-11-28 10:09 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +      if (!user) {
Je ne suis pas certain que l'utilisateur puisse être introuvable. La méthode utilisé avant est censée le créer si il est introuvable. Il ne peut donc jamais être introuvable après ?

2024-11-28 10:11 UTC, thomashbrnrd commented on server/src/auth/get-user.decorator.ts
> +export const GetUser = createParamDecorator(
Est ce que cette function est utilisée ?

2024-11-28 10:11 UTC, thomashbrnrd commented on server/src/auth/jwt-payloard.interface.ts
> +export interface JwtPayload {
Est ce que c'est utilisé ?

2024-11-28 10:13 UTC, thomashbrnrd commented on server/src/external-source/external-source.controller.ts
> +    const ownerId = 'f15d1c13-8198-4ca5-a180-94656e20d568';
Est ce que c'est normal d'avoir ce `ownerId` en "dur" ici ?

2024-11-28 10:15 UTC, thomashbrnrd commented on server/src/user/user.controller.ts
> +  // @Post()
Peux-être que l'on peut supprimer ces commentaires ?

2024-11-28 11:20 UTC, Carolinedanslesnuages commented on server/src/external-source/external-source.controller.ts
> +    const ownerId = 'f15d1c13-8198-4ca5-a180-94656e20d568';
j'ai corrigé

2024-11-28 12:39 UTC, Carolinedanslesnuages commented on server/src/application/application.controller.ts
> +  private getDecodedToken(req: any): any {
On peut voir ensemble après le daily? 
c'est la fonction qu'on a fait ensemble hier  qui permet de décoder le token pour obtenir email et sub ... que j'ai simplement sorti de la methode create pour plus de lisibilité

2024-11-28 12:42 UTC, thomashbrnrd commented on server/src/utils/auth.utils.ts
> +      throw new UnauthorizedException('En-tête Authorization manquant');
Improbable car KrakenD s'en occupe.

2024-11-28 12:42 UTC, thomashbrnrd commented on server/src/utils/auth.utils.ts
> +      throw new UnauthorizedException('Token Bearer non fourni');
Improbable car KrakenD s'en occupe.

2024-11-28 12:43 UTC, thomashbrnrd commented on server/src/utils/auth.utils.ts
> +      throw new UnauthorizedException('JWT invalide ou malformé');
Improbable car KrakenD s'en occupe.

2024-11-28 12:44 UTC, thomashbrnrd commented on server/src/utils/auth.utils.ts
> +      throw new UnauthorizedException('JWT manquant de claims requis (email ou sub)');
Cela me semble également improbable, ce serait une erreur de configuration de keycloak, as code en plus ... Donc je ne pense pas que cette exception soit nécessaire.

2024-11-28 12:46 UTC, thomashbrnrd commented on server/src/external-source/external-source.controller.ts
> +      throw new InternalServerErrorException(
Je ne pense pas que ce soit utile de gérer une "erreur interne". Documentation : https://docs.nestjs.com/exception-filters

2024-11-28 15:52 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +    Logger.log('create method called');
Est ce qu'on veut vraiment garder ce log ? Il sera afficher de toutes manières dans les logs du backend que cette endpoint aura été appelé non ?

2024-11-28 15:53 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +    console.log(searchParams);
Est ce que c'est fait exprès de conserver ce `console.log()` ?

2024-11-28 15:54 UTC, Carolinedanslesnuages commented on server/src/application/application.controller.ts
> +    console.log(searchParams);
nope 😶‍🌫️

2024-11-28 15:55 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +      throw new UnauthorizedException('En-tête Authorization manquant');
Comme signalé auparavant, cette exception ne sert à rien car KrakenD gère déjà cette situation.

2024-11-29 10:09 UTC, thomashbrnrd approved these changes

2024-11-29 10:18 UTC, merged