feat: :sparkles: backEnd route get all applications
dnum-mi/referentiel-applications pull request #172
Opened 2024-12-18 10:09 UTC by KomsteRr

2024-12-19 09:38 UTC, thomashbrnrd requested changes

2024-12-19 09:38 UTC, thomashbrnrd commented on server/src/application/application.controller.ts
> +  async getApplications() {
Ce serait mieux je pense d'utiliser la nomenclature de NestJS pour les noms des fonctions des controllers : 
```js
import { Controller, Get, Query, Post, Body, Put, Param, Delete } from '@nestjs/common';
import { CreateCatDto, UpdateCatDto, ListAllEntities } from './dto';

@Controller('cats')
export class CatsController {
  @Post()
  create(@Body() createCatDto: CreateCatDto) {
    return 'This action adds a new cat';
  }

  @Get()
  findAll(@Query() query: ListAllEntities) {
    return `This action returns all cats (limit: ${query.limit} items)`;
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return `This action returns a #${id} cat`;
  }

  @Put(':id')
  update(@Param('id') id: string, @Body() updateCatDto: UpdateCatDto) {
    return `This action updates a #${id} cat`;
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return `This action removes a #${id} cat`;
  }
}
```

2024-12-19 09:38 UTC, thomashbrnrd commented on server/src/application/application.service.ts
> +    const applicationsList = await this.prisma.application.findMany();
Pourquoi ne pas faire directement : 
```js
return await this.prisma.application.findMany();
```
?

2025-01-14 13:29 UTC, Carolinedanslesnuages approved these changes

2025-01-14 13:30 UTC, merged